name: Mypy (quick)

on:
  push:
    paths:
      - 'rag-advanced/app/**/*.py'
      - 'rag-advanced/pyproject.toml'
      - '.github/workflows/mypy.yml'
  pull_request:

concurrency:
  group: mypy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rag-advanced
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install project (dev,offline)
        shell: bash
        run: |
          uv --version
          uv pip install -e ".[dev,offline]"

      - name: Mypy
        shell: bash
        run: uv run mypy app
